### ISSUE TITLE
playerStateChanged event not triggered

### ISSUE THREAD

**Issue by Summys** [cjam/react-native-spotify-remote#14]
Have you bridged the entire sdk? I can't find some useful functions like subscribing to player's state and disconnect the user.

You did an awesome job with this package, and please let me know if I can help you with something.

Edit: The listener for 'playerStateChanged' isn't triggered, remoteConnected and remoteDisconnected works properly, but I have hard times listening to player's change

**Comment by cjam** [comment]
Hey sorry for the huge delay, I've been traveling around the world for the past 4 months and am getting back into this repo.  

I believe I bridged most of the functionality exposed by the ios sdk, but then spotify has likely released some updates to the SDK since that need to be incorporated.  My plan is to first get this repo working with CocoaPods and update to the latest SDK.

I'll be going through everything again, so I'll make sure that the playerStateChanged stuff is working.  Stay tuned.

**Comment by cjam** [comment]
This should be fixed in v0.1.0

**Comment by garethleonard** [comment]
I am still seeing this in 0.2.2. Should the playerStateChanged event be triggered on pausing the track?

**Comment by cjam** [comment]
yep it should.  I'm currently using this library in an app I'm building and use the playerStateChanged event heavily

**Comment by garethleonard** [comment]
```
remote.addListener('playerStateChanged', event => {
  console.log(event);
});
```
This should do the trick, right?

**Comment by cjam** [comment]
I would think so ya.  This is where I'm doing it in the example app for reference:

https://github.com/cjam/react-native-spotify-remote/blob/39899b92ca9c1762517ea1f45ff57ac95a35d8a0/example/AppContext.tsx#L71

I created the example app for manually testing and also giving examples of each part of the library.

**Comment by garethleonard** [comment]
Thanks. I'm sure it's my issue here. Will play around with it. Thanks for the great work!

**Comment by garethleonard** [comment]
Got it working. I was setting the wrong values on state so my UI wasn't updating. Follow-up question - should the event trigger when the playbackPosition updates? I want to keep track of a seek bar without having to keep my own timer.

**Comment by cjam** [comment]
@garethleonard Unfortunately it does not.  I have however wired up the playerStateChanged event so that if you request the current playerState it will fire that event when the state comes back.  So a work around is you should be able to put `remote.getPlayerState()` on a timer but handle all the state changes in your event handler like you are now.  Hope that makes sense.
