### ISSUE TITLE
[Error: null] in Console Error after obtaining the token

### ISSUE THREAD

**Issue by Sebas3245** [cjam/react-native-spotify-remote#65]
Hello, great project, I have a problem, when I want to do: **await SpotifyRemote.connect(session.accessToken);**
the error catcher gets the following problem and I don't know how to fix it **[Error: null]**
This happens after obtaining the access token that when checking in the console the token is obtained correctly, the error occurs in the connect method

I want to emphasize that if I have defined the scope: **ApiScope.AppRemoteControlScope**

I need help, I would really appreciate an answer.

**Comment by cjam** [comment]
ah I think this might be a bug in the way that I've implemented this.  Just to confirm, is this in iOS or android?

**Comment by Sebas3245** [comment]
Try to request the token in the way explained in the documentation and from the WEB API, it still does not connect and the same error appears, the same error occurs to my fellow developers

I am on android


I am using a free spotify account, can that affect it?

**Comment by Sebas3245** [comment]
![dddd](https://user-images.githubusercontent.com/55991750/88818781-b4f40280-d184-11ea-9183-e7116b0f4d5c.png)
![sss](https://user-images.githubusercontent.com/55991750/88818786-b6252f80-d184-11ea-8254-9543553194f2.png)

**Comment by arthurhts** [comment]
Some interim solution to the problem?

**Comment by cmpayc** [comment]
**react-native-spotify-remote** returns **[Error: null]** if your phone (or emulator) doesn't have the Spotify app installed.
You can debug it in Android Studio. Errors returns in Spotify SDK, in file `com/spotify/android/appremote/api/LocalConnector.class`:
```Java
if (!this.mSpotifyLocator.isSpotifyInstalled(context)) {
            connectionListener.onFailure(new CouldNotFindSpotifyApp());
} 
```

**Comment by cjam** [comment]
Ah yes good catch @cmpayc.  I think it would probably be best if this library checked to see if spotify was installed and returned a more sensible error.  

@Sebas3245 @arthurhts can you confirm that you are indeed using this on a device that has spotify installed?  Any other details of the environment will help when doing error checking

**Comment by cjam** [comment]
I believe this should be addressed by the #82 from @djwillcaine.  I am also working on exposing better error messages from iOS as well as adding a check to see if spotify is installed in iOS.  Will Close this when there is a version out.
